name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: set up JDK 21
      uses: actions/setup-java@main
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew app:assembleRelease
        
    - name: Rename signed apk
      run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/ChromeXt.apk

    


    - name: Collect signed APK
      uses: actions/download-artifact@main
      with:
        name: ChromeXt.apk
